// src/components/app/footer.tsx

'use client';

import * as React from 'react';
import { Github, Sparkles, GitPullRequestCreate } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import useLicenseCheck from '@/hooks/useLicenseCheck';
import LockScreen from '@/components/app/LockScreen';
import { Label } from '../ui/label';
import { Input } from '../ui/input';
import { Textarea } from '../ui/textarea';

const GradientButton = React.forwardRef<
  HTMLButtonElement,
  React.ComponentProps<typeof Button>
>(({ children, className, ...props }, ref) => (
  <Button
    ref={ref}
    className="bg-gradient-to-r from-accent to-primary text-primary-foreground hover:opacity-90 transition-opacity"
    {...props}
  >
    {children}
  </Button>
));
GradientButton.displayName = 'GradientButton';

type AppFooterProps = {
    onPublish?: () => void;
    onPullRequest?: (details: { title: string, body: string }) => void;
    isPublishing: boolean;
    isCreatingPr: boolean;
};

export function AppFooter({ onPublish, onPullRequest, isPublishing = false, isCreatingPr = false }: AppFooterProps) {
  const isLocked = useLicenseCheck();
  const [prDialogOpen, setPrDialogOpen] = React.useState(false);
  const [prTitle, setPrTitle] = React.useState('Jekyll Buildr Updates');
  const [prBody, setPrBody] = React.useState('This pull request was automatically generated by Jekyll Buildr.');

  const handleCreatePr = () => {
    if (onPullRequest) {
      onPullRequest({ title: prTitle, body: prBody });
    }
  };

  return (
    <>
    <footer className="flex flex-col-reverse w-full gap-2 md:flex-row h-18 md:h-[65px] shrink-0 items-center justify-between border-t py-3 px-2 lg:px-6">
      <span id="appFooter" style={{ display: isLocked ? 'none' : 'block', width: '100%' }} className='text-sm md:text-md text-gray-900 dark:text-orange-400 w-full'>Jekyll Buildr by Daffa</span>
      <div className='flex justify-between items-center w-full md:justify-end md:gap-4'>
      {onPullRequest && (
        <Dialog open={prDialogOpen} onOpenChange={setPrDialogOpen}>
          <DialogTrigger asChild>
            <Button variant="outline" className='size-sm' disabled={isCreatingPr || isPublishing}>
              <GitPullRequestCreate className="mr-2" />
              {isCreatingPr ? 'Creating PR...' : 'Pull Request'}
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[400px]">
            <DialogHeader>
              <DialogTitle>Create Pull Request</DialogTitle>
              <DialogDescription>
                Review your changes and create a pull request to merge them into your main branch.
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid grid-rows items-center gap-4">
                <Label htmlFor="pr-title" className="text-left">
                  Title
                </Label>
                <Input
                  id="pr-title"
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  className="col-span-3"
                />
              </div>
              <div className="grid grid-rows items-start gap-4">
                <Label htmlFor="pr-body" className="text-left mt-2">
                  Description
                </Label>
                <Textarea
                  id="pr-body"
                  value={prBody}
                  onChange={(e) => setPrBody(e.target.value)}
                  className="col-span-3"
                  rows={4}
                />
              </div>
            </div>
            <DialogFooter>
              <Button onClick={handleCreatePr} className='size-sm' disabled={isCreatingPr || !prTitle}>
                {isCreatingPr && <Sparkles className="mr-2 h-4 w-4 animate-pulse" />}
                Pull Request
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {onPublish && (
        <GradientButton onClick={onPublish} disabled={isPublishing || isCreatingPr}>
            {isPublishing ? (
            <>
                <Sparkles className="mr-2 h-4 w-4 animate-pulse" />
                Publishing...
            </>
            ) : (
            <>
                <Github className="mr-2" />
                Push to GitHub
            </>
            )}
        </GradientButton>
      )}
      </div>
    </footer>
    {isLocked && <LockScreen />}
    </>
  );
}
